name: Beautiful Jekyll CI
on:
  push:
    branches: ['master']
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the site in the jekyll/builder container
        run: |
          export JEKYLL_VERSION=3.8
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "\
          apk update && \
          apk add --no-cache ruby=2.5.9-r0 ruby-dev=2.5.9-r0 ruby-bundler build-base && \
          bundle config set --local path 'vendor/bundle' && \
          bundle install && \
          chmod 777 /srv/jekyll && \
          jekyll build --future"
